### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ewnd9** [ewnd9/media-center#3]
## omxplayer/playlists
- [ ] playlist logic: 
  - play from folder: playlist == folder
  - play random videos: playlist === all unwatched videos
  - play from youtube: playlist === youtube playlist
## ui
- [ ] hotkeys list tooltip (also it's possible to show them on top of omxplayer)
- [ ] version and commit hash in the footer
## ui - files tree
- [ ] "Play random" button at the top filter, 
- [x] Reload files on "mark as watched" action
- [x] Delete button, but move to "trash" folder instead of the physical deletion
## ui - screenshots gallery
- [ ] delete from gallery button
- [ ] pagination
- [ ] infinity feed
## omxplayer
- [x] hide playback status interface (no bias to continue watching only because already watch a half)
- [ ] auto select last audio track
- [ ] testing: mock OMX emitter to send progress events
## hotkeys
- [x] take a screenshot of playing video
- [ ] next episode in folder
- [ ] volume control
- [ ] explore  https://github.com/jaruba/PowderPlayer/wiki/Hotkeys
- [ ] more precise position nagivation, now only +- 30 seconds 
## transcoding

plex example https://hub.docker.com/r/besn0847/arm-plex/
## trakt integration
- [ ] ~~Store failed check-in requests with dates. Check on every request if there are any failed, send them first~~ show list of files with progress > 80% and no scrobble, manually apply (maybe batch with checkboxes)
## youtube integration
- [x] basic integration https://github.com/ewnd9/media-center/commit/038dce2720ad85c48472d00d5e9e2052eb5d9562
- [x] explore ways to authorize and get subscribed channels videos
  - react youtube search http://hackingbeauty.com/react-youtube-autocomplete/ 
- [ ] explore ways to share video from the youtube android app to media-center 
  - https://github.com/fcannizzaro/remote-tile (cyanogen-mode)
  - https://play.google.com/store/apps/details?id=com.kiwiidev.raspberrycast (from https://github.com/vincelwt/RaspberryCast)
    - hard-coded 2020 port
    - can't find the source code for the android app 
  - https://github.com/RikardLegge/Pi-mediacaster
    - seems nice
    - can't find an apk
  - https://github.com/AdityaNG/PiCast
    - has an apk in the repository
    - can't find share-related code, only opening urls in the web view
## remote control
- [ ] setup ssl via letsencrypt (for an implementation of a service worker), send [a push notification](https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web) to Chrome on start playing with [actions](https://notifications.spec.whatwg.org/#using-actions) like play/pause to `media-center`
